os: linux
services:
  - docker

dist: bionic
arch:
  - amd64
  - arm64
env:
  - TRAVIS_CPU_ARCH=arm64
  - TRAVIS_CPU_ARCH=amd64
language: minimal
jobs:
  include:
    - stage: build 
      script: ./.ci/build.sh
      env: TRAVIS_CPU_ARCH=arm64
    - stage: e2e-test
      install: ./.ci/e2e-test/setup.sh
      if: tag IS present OR commit_message =~ /perform-e2e/
      script: ./.ci/e2e-test/test.sh
      env: TRAVIS_CPU_ARCH=arm64
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - MINIKUBE_WANTUPDATENOTIFICATION=false
        - MINIKUBE_WANTREPORTERRORPROMPT=false
        - MINIKUBE_HOME=$HOME
        - CHANGE_MINIKUBE_NONE_USER=true
        - KUBECONFIG=$HOME/.kube/config
    - stage: publish
      script: ./.ci/publish.sh
      env: TRAVIS_CPU_ARCH=arm64
