os: linux
services:
  - docker

dist: bionic

language: minimal

jobs:
  include:
    - stage: build 
      arch:
         - arm64
         - amd64
      script: ./.ci/build.sh
    - stage: e2e-test
      arch:
         - arm64
         - amd64
      install: ./.ci/e2e-test/setup.sh
      script: ./.ci/e2e-test/test.sh
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - MINIKUBE_WANTUPDATENOTIFICATION=false
        - MINIKUBE_WANTREPORTERRORPROMPT=false
        - MINIKUBE_HOME=$HOME
        - CHANGE_MINIKUBE_NONE_USER=true
        - KUBECONFIG=$HOME/.kube/config
    - stage: publish
      arch:
         - arm64
         - amd64
      script: ./.ci/publish.sh
