os: linux
services:
  - docker

dist: bionic

language: minimal

jobs:
  include:
    - stage: build 
      script: ./.ci/build.sh
      env:
        - matrix:
              - arch=amd64
              - arch=arm64
    - stage: e2e-test
      install: ./.ci/e2e-test/setup.sh
      if: tag IS present OR commit_message =~ /perform-e2e/
      script: ./.ci/e2e-test/test.sh
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - MINIKUBE_WANTUPDATENOTIFICATION=false
        - MINIKUBE_WANTREPORTERRORPROMPT=false
        - MINIKUBE_HOME=$HOME
        - CHANGE_MINIKUBE_NONE_USER=true
        - KUBECONFIG=$HOME/.kube/config
        - matrix:
              - arch=amd64
              - arch=arm64
    - stage: publish
      script: ./.ci/publish.sh
      env:
        - matrix:
              - arch=amd64
              - arch=arm64
